"""
TaskPilot AI - Main API Entry Point
This module handles all FastAPI routes, middleware configuration, and request lifecycle management.
It utilizes asynchronous patterns for high-performance AI processing and database operations.
"""

import time
import os
import logging
from fastapi import FastAPI, Depends, HTTPException
from fastapi.staticfiles import StaticFiles
from fastapi.middleware.cors import CORSMiddleware
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from pydantic import BaseModel
from dotenv import load_dotenv

# Internal module imports
from backend.database import engine, Base, get_db, History
from agents.agent import (
    analyze_resume_tool,
    devops_generator_tool,
    daily_planner_tool,
    notes_summarizer_tool,
    blog_writer_tool,
    interview_questions_tool,
    route_and_execute
)

# Initialize logging for production-grade observability
logging.basicConfig(
    level=logging.INFO, 
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger("TaskPilot")

# Load environment variables from .env file
load_dotenv()

# Initialize FastAPI application
app = FastAPI(
    title="TaskPilot AI API",
    description="A production-ready Multi-Agent AI productivity platform.",
    version="1.0.0"
)

# Configure Cross-Origin Resource Sharing (CORS) for frontend integration
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"], # In production, replace with specific domain names
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# --- Request/Response Schemas (Pydantic Models) ---

class InputData(BaseModel):
    """Standard input schema for single-tool execution."""
    text: str

class AgentInput(BaseModel):
    """Input schema for the intelligent routing agent."""
    user_input: str

# --- Helper Functions ---

async def save_history(db: AsyncSession, tool_name: str, user_input: str, ai_output: str, latency: int):
    """
    Saves the result of an AI interaction to the database for history and LLMOps monitoring.
    
    Args:
        db (AsyncSession): The database session.
        tool_name (str): The name of the AI tool used.
        user_input (str): The original user prompt.
        ai_output (str): The response generated by the LLM.
        latency (int): Time taken for the request in milliseconds.
    """
    try:
        history_entry = History(
            tool_name=tool_name, 
            user_input=user_input, 
            ai_output=ai_output,
            model_name="gemini-2.5-flash",
            latency_ms=latency
        )
        db.add(history_entry)
        await db.commit()
    except Exception as e:
        logger.error(f"Failed to save history to database: {e}")
        await db.rollback()

# --- Lifecycle Hooks ---

@app.on_event("startup")
async def startup():
    """Logic to execute when the server starts (e.g., creating DB tables)."""
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    logger.info("TaskPilot Backend successfully started and database initialized.")

# --- API Endpoints ---

@app.post("/api/agent")
async def agent_endpoint(data: AgentInput, db: AsyncSession = Depends(get_db)):
    """
    The 'Smart Agent' entry point. Routes input to the appropriate specialized tool.
    """
    start_time = time.time()
    try:
        # Step 1: Route to the correct tool and execute logic
        tool_name, output = await route_and_execute(data.user_input)
        
        # Step 2: Calculate performance metrics
        latency = int((time.time() - start_time) * 1000)
        
        # Step 3: Log metadata and save to DB
        await save_history(db, tool_name, data.user_input, output, latency)
        
        return {"tool_name": tool_name, "output": output, "latency": latency}
    except Exception as e:
        logger.error(f"Critical error in Agent endpoint: {e}")
        raise HTTPException(status_code=500, detail="The AI Agent encountered an internal error.")

@app.get("/api/history")
async def get_history(db: AsyncSession = Depends(get_db)):
    """
    Retrieves the chronological history of AI interactions.
    """
    try:
        # Fetch data using async SQLAlchemy 2.0 select syntax
        result = await db.execute(select(History).order_by(History.created_at.desc()))
        history = result.scalars().all()
        
        return {
            "history": [
                {
                    "id": h.id,
                    "tool_name": h.tool_name,
                    "user_input": h.user_input,
                    "ai_output": h.ai_output,
                    "model_name": h.model_name,
                    "latency_ms": h.latency_ms,
                    "created_at": h.created_at.isoformat() if h.created_at else None
                } for h in history
            ]
        }
    except Exception as e:
        logger.error(f"Failed to retrieve history: {e}")
        return {"history": [], "error": "History unavailable."}

# --- Static Content ---

# Serve the frontend files if they exist in the project directory
frontend_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), "frontend")
if os.path.exists(frontend_path):
    app.mount("/", StaticFiles(directory=frontend_path, html=True), name="frontend")
